'\" -*- coding: utf-8 -*-
'\" vim:fenc=utf-8
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH ayatana-settings 8 "Oct 2023" "Version 23.10.13" "Ayatana Indicators Settings"
.SH NAME
ayatana-settings \- Fine-tune behaviour of Ayatana System Indicators
.SH SYNOPSIS
'nh
.fi
.ad l
\fBayatana-settings\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[
\fIoptions\fR
]
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
Ayatana (System) Indicators are a set of notification tray icons that are
available for desktop environments that provide an Indicator Renderer
applet. With Ayatana System Indicators users can get easy access to
various system properties and settings (e.g. sound, events, messages and
notifications, session management, bluetooth, etc.).
.PP
\fBayatana-settings\fR is a graphical tool supplementing the desktop
environment's control center / settings area and allows the user to
fine-tune the behaviour of Ayatana System Indicators.
.SH COMMON OPTIONS
\fBayatana-settings\fR does not have any command line options (except
those provided by standard GTK applications).
.SH "FILES"
~/.config/autostart/ayatana-indicator-*.desktop
.PP
.SH AUTHOR
This manual has been written for the Ayatana Indicators project by Mike
Gabriel <mike.gabriel@das-netzwerkteam.de>.
